import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//FALTA COMPROBAR SI HAY TOKEN AL ENTRAR EN LA APP Y REDIRIGIR EN FUNCIÓN DE ESO
export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="es">
      <body>
        <AuthProvider>
        <main>
          {children}
        </main>
        </AuthProvider>
      </body>
    </html>
  );
}
